const fs = require('fs');
const jp_en = 'c:/Users/sudxx/OneDrive/Desktop/Asterisk-AI-Voice-Agent/admin_ui/frontend/src/locales/en.json';
const j_en = JSON.parse(fs.readFileSync(jp_en, 'utf8'));

const addKeys = (j) => {
    if (!j.advanced) j.advanced = {};

    j.advanced.llm = {
        title: "LLM Defaults",
        desc: "Set default parameters for Large Language Model interactions.",
        saveSuccess: "LLM configuration saved",
        saveFailed: "Failed to save configuration",
        restartWarning: "LLM configuration changes require an AI Engine restart to take effect.",
        restarting: "Restarting...",
        restartAIEngine: "Restart AI Engine",
        restartSuccess: "AI Engine restarted! Changes are now active.",
        saving: "Saving...",
        saveChanges: "Save Changes",
        defaultParamsTitle: "Default Parameters",
        defaultParamsDesc: "Fallback settings when not specified by a context.",
        initialGreetingLabel: "Initial Greeting",
        initialGreetingPlaceholder: "Hello, how can I help you today?",
        initialGreetingTooltip: "The first message spoken by the AI when the call starts.",
        systemPromptLabel: "System Prompt",
        systemPromptPlaceholder: "You are a helpful AI assistant...",
        systemPromptDesc: "The core personality and instructions for the AI."
    };

    j.advanced.rawYaml = {
        title: "Raw Configuration",
        desc: "Directly edit the AI agent configuration. Changes are saved to `ai-agent.local.yaml` (your operator overrides).",
        importBtn: "Import",
        exportBtn: "Export",
        saveChanges: "Save Changes",
        saving: "Saving...",
        importTitle: "Import Configuration?",
        importDesc: "This will overwrite your current configuration. A backup will be created.",
        importSuccess: "Configuration imported successfully. The page will reload.",
        importFailed: "Failed to import configuration",
        exportSuccess: "Configuration exported successfully",
        exportFailed: "Failed to export configuration",
        saveSuccess: "Configuration saved successfully",
        errorLoading: "Failed to load configuration",
        yamlSyntaxError: "YAML Syntax Error - Fix below and save",
        location: "Location",
        line: "Line",
        column: "Column",
        problem: "Problem"
    };

    j.advanced.streaming = {
        title: "Streaming Settings",
        desc: "Fine-tune real-time audio streaming performance and latency.",
        saveSuccess: "Streaming configuration saved",
        saveFailed: "Failed to save configuration",
        restartWarning: "Changes to streaming configurations require an AI Engine restart to take effect.",
        restarting: "Restarting...",
        reloadAIEngine: "Reload AI Engine",
        restartSuccess: "AI Engine restarted! Changes are now active.",
        saving: "Saving...",
        saveChanges: "Save Changes",
        playbackModeTitle: "Playback Mode",
        playbackModeDesc: "Choose how AI responses are delivered to callers.",
        downstreamModeLabel: "Downstream Mode",
        downstreamModeTooltip: "Use 'stream' for production (low latency). Use 'file' for debugging playback issues.",
        downstreamModeStream: "Streaming (Real-time)",
        downstreamModeFile: "File-based (Debugging)",
        audioStreamParamsTitle: "Audio Stream Parameters",
        audioStreamParamsDesc: "Core settings for audio packet handling.",
        chunkSizeLabel: "Chunk Size (ms)",
        chunkSizeTooltip: "Duration of each audio packet.",
        sampleRateLabel: "Sample Rate",
        sampleRateTooltip: "Audio sampling rate (Hz).",
        jitterBufferLabel: "Jitter Buffer (ms)",
        jitterBufferTooltip: "Buffer to smooth out network variations.",
        connTimeoutLabel: "Connection Timeout (ms)",
        connTimeoutTooltip: "Maximum time to wait for provider connection before failing (default: 120000ms = 2 min).",
        keepaliveLabel: "Keepalive Interval (ms)",
        keepaliveTooltip: "How often to send keepalive pings to prevent connection timeout (default: 5000ms).",
        graceLabel: "Provider Grace Period (ms)",
        graceTooltip: "Wait time for provider response before considering it unresponsive (default: 200ms).",
        fallbackLabel: "Fallback Timeout (ms)",
        fallbackTooltip: "Time before switching to fallback provider if primary fails (default: 8000ms).",
        lowWatermarkLabel: "Low Watermark (ms)",
        lowWatermarkTooltip: "Minimum audio buffered before playback starts - lower = faster but may be choppy (default: 80ms).",
        minStartLabel: "Min Start (ms)",
        minStartTooltip: "Minimum audio required before starting response playback (default: 120ms).",
        greetMinStartLabel: "Greeting Min Start (ms)",
        greetMinStartTooltip: "Reduced min start for greetings - faster initial response (default: 40ms).",
        greetRtpWaitLabel: "Greeting RTP Wait (ms)",
        greetRtpWaitTooltip: "ExternalMedia only: How long to wait for RTP endpoint before falling back to file playback for greeting (default: 250ms). Increase if greetings are cut off.",
        emptyBackoffLabel: "Empty Backoff Ticks Max",
        emptyBackoffTooltip: "Max retries when buffer is empty before pausing playback (default: 5).",
        contStreamLabel: "Continuous Stream",
        contStreamDesc: "Keep the stream open even during silence.",
        normTitle: "Audio Normalizer",
        normDesc: "Normalize audio levels for consistent volume.",
        enableNormLabel: "Enable Normalizer",
        enableNormDesc: "Automatically adjust audio gain.",
        maxGainLabel: "Max Gain (dB)",
        maxGainTooltip: "Maximum volume boost applied to quiet audio (default: 18dB).",
        targetRmsLabel: "Target RMS",
        targetRmsTooltip: "Target audio level for normalization - higher = louder output (default: 1400).",
        egressTitle: "Egress Format",
        egressDesc: "Control audio byte ordering and format for downstream playback.",
        egressSwapLabel: "Egress Swap Mode",
        egressSwapTooltip: "Controls PCM16 byte ordering for downstream playback. 'auto' detects system endianness. Use 'swap' if audio sounds garbled/static, 'none' if already correct.",
        swapModeAuto: "Auto (detect from system)",
        swapModeSwap: "Swap (force byte swap)",
        swapModeNone: "None (no byte swap)",
        forceMulawLabel: "Force μ-law Encoding",
        forceMulawDesc: "Always encode egress audio as μ-law regardless of profile.",
        forceMulawTooltip: "Force μ-law (G.711) encoding for all downstream audio. Enable if Asterisk expects μ-law but provider sends PCM16. Typically needed for telephony compatibility.",
        diagTitle: "Diagnostics",
        diagDesc: "Tools for debugging audio stream issues.",
        enableTapsLabel: "Enable Audio Taps",
        enableTapsDesc: "Record raw audio streams to disk for analysis.",
        outDirLabel: "Output Directory",
        outDirTooltip: "Directory to save diagnostic audio recordings.",
        preSecsLabel: "Diag Pre Seconds",
        preSecsTooltip: "Seconds of audio to capture before an event (default: 1).",
        postSecsLabel: "Diag Post Seconds",
        postSecsTooltip: "Seconds of audio to capture after an event (default: 1)."
    };

    j.advanced.transport = {
        title: "Audio Transport",
        desc: "Configure how audio is transported between Asterisk and the AI Agent.",
        hotReloadSaved: "Configuration saved. Changes can be applied via hot-reload.",
        restartSaved: "Transport configuration saved. Restart AI Engine to apply changes.",
        saveFailed: "Failed to save configuration",
        hotReloadAppliedPartiallyWarn: "Hot reload applied partially",
        hotReloadAppliedPartiallyDesc: "Restart AI Engine to fully apply changes",
        hotReloadSuccess: "AI Engine hot reloaded! Changes are now active.",
        hotReloadRes: "Hot reload response:",
        forceRestartTitle: "Force Restart?",
        forceRestartDesc: "Do you want to force restart anyway? This may disconnect active calls.",
        forceRestartConfirm: "Force Restart",
        restartedDegradedWarn: "AI Engine restarted but may not be fully healthy",
        restartedDegradedDesc: "Please verify manually",
        restartSuccess: "AI Engine restarted! Changes are now active.",
        failedAction: "Failed to",
        bannerHotReload: "Changes saved. Apply Changes to hot reload AI Engine without a restart.",
        bannerRestart: "Changes to transport configurations require an AI Engine restart to take effect.",
        applying: "Applying...",
        applyChanges: "Apply Changes",
        restartAIEngine: "Restart AI Engine",
        saving: "Saving...",
        saveChanges: "Save Changes",
        astConfigTitle: "Asterisk Configuration",
        astConfigDesc: "Core Asterisk integration settings.",
        stasisAppLabel: "Stasis Application Name",
        stasisAppTooltip: "Name of the Stasis application in your dialplan. Must match the app name in your Asterisk configuration.",
        transTypeTitle: "Transport Type",
        transTypeDesc: "Select the audio transport method.",
        transMethodLabel: "Transport Method",
        transMethodDesc: "Choose 'AudioSocket' for standard deployments or 'External Media' for RTP-based integration.",
        transAudioSocket: "AudioSocket (Default)",
        transExtMedia: "External Media (RTP)",
        asSettingsTitle: "AudioSocket Settings",
        asSettingsDesc: "Configuration for the AudioSocket server.",
        networkConfigLabel: "Network Configuration",
        bindHostLabel: "Bind Host",
        bindHostTooltip: "IP address the AudioSocket server listens on. Use 0.0.0.0 to listen on all interfaces.",
        advHostLabel: "Advertise Host",
        advHostTooltip: "IP address Asterisk connects to. For NAT/VPN deployments, set this to your routable IP (VPN IP, public IP, or LAN IP). Leave as Bind Host for same-host deployments.",
        portLabel: "Port",
        portTooltip: "TCP port for AudioSocket connections (default: 8090).",
        formatLabel: "Format",
        formatTooltip: "Audio format (e.g., slin, ulaw)",
        extSettingsTitle: "External Media (RTP) Settings",
        extSettingsDesc: "Configuration for RTP-based audio transport.",
        rtpBindHostLabel: "RTP Bind Host",
        rtpBindHostTooltip: "IP address the RTP server listens on. Use 0.0.0.0 to listen on all interfaces.",
        rtpAdvHostTooltip: "IP address Asterisk sends RTP to. For NAT/VPN deployments, set this to your routable IP (VPN IP, public IP, or LAN IP). Leave as Bind Host for same-host deployments.",
        rtpPortLabel: "RTP Port",
        rtpPortTooltip: "Base UDP port for RTP streams (default: 18080).",
        portRangeLabel: "Port Range",
        portRangeTooltip: "Range of UDP ports for concurrent calls (format: start:end, e.g., 18080:18099).",
        allowedHostsLabel: "Allowed Remote Hosts",
        allowedHostsTooltip: "IP addresses allowed to send RTP packets. Required when ASTERISK_HOST is a hostname. Comma-separated for multiple IPs.",
        astSideConfigLabel: "Asterisk-side Configuration",
        codecLabel: "Codec",
        codecDesc: "Codec Asterisk sends/receives.",
        dirLabel: "Direction",
        engineSideConfigLabel: "Engine-side Configuration",
        internalFormatLabel: "Internal Format",
        internalFormatDesc: "Engine internal format. Pipelines typically expect 16kHz PCM16 (slin16).",
        sampleRateHzLabel: "Sample Rate (Hz)",
        sampleRateHzTooltip: "Auto-inferred from format if not set.",
        extExpertLabel: "External Media Expert Settings",
        extExpertDesc: "Expose RTP source endpoint hardening controls.",
        extExpertWarn: "Warning: incorrect settings can drop RTP packets or break media connectivity.",
        extExpertReadOnly: "Expert values are visible and read-only until enabled.",
        lockRemoteLabel: "Lock Remote Endpoint",
        lockRemoteDesc: "Drop RTP packets if source host/port changes mid-call.",
        lockRemoteHardening: "Security hardening: keep enabled unless your network path legitimately rewrites RTP source mid-call.",
        ulawCodec: "μ-law (8kHz)",
        alawCodec: "A-law (8kHz)",
        slinCodec: "SLIN (8kHz)",
        slin16Codec: "SLIN16 (16kHz)",
        dirBoth: "Both",
        dirSendOnly: "Send Only",
        dirRecvOnly: "Receive Only"
    };

    j.advanced.vad = {
        title: "Voice Activity Detection",
        desc: "Configure how the system detects speech and silence.",
        saveSuccess: "VAD configuration saved",
        saveFailed: "Failed to save configuration",
        restartWarning: "Changes to VAD configurations require an AI Engine restart to take effect.",
        restarting: "Restarting...",
        reloadAIEngine: "Reload AI Engine",
        forceRestartTitle: "Force Restart?",
        forceRestartDesc: "Do you want to force restart anyway? This may disconnect active calls.",
        forceRestartConfirm: "Force Restart",
        restartedDegradedWarn: "AI Engine restarted but may not be fully healthy",
        restartedDegradedDesc: "Please verify manually",
        restartSuccess: "AI Engine restarted! Changes are now active.",
        saving: "Saving...",
        saveChanges: "Save Changes",
        primaryDetectTitle: "Primary Detection",
        primaryDetectDesc: "Main VAD settings for speech detection.",
        enhVadLabel: "Enhanced VAD",
        enhVadDesc: "Use advanced algorithms for better accuracy.",
        enhVadTooltip: "Enables engine-side VAD (energy + optional WebRTC VAD) used for local heuristics like barge-in fallback and silence robustness. Does not change provider-owned turn-taking.",
        useProvVadLabel: "Use Provider VAD",
        useProvVadDesc: "Prefer provider-managed turn detection when supported; engine VAD is used only for local fallback heuristics.",
        useProvVadTooltip: "When enabled, the engine avoids making primary turn/endpointing decisions and relies on provider-side detection where available. Engine VAD may still be used for safe local fallbacks.",
        energyThreshLabel: "Energy Threshold (RMS)",
        energyThreshTooltip: "Engine VAD energy threshold (RMS over PCM16). Higher = less sensitive (fewer false triggers), lower = more sensitive (better for quiet callers). Only applies when Enhanced VAD is enabled.",
        confThreshLabel: "Confidence Threshold",
        confThreshTooltip: "Confidence required for engine VAD decisions (0.0–1.0). Used by engine heuristics; providers may implement their own confidence/endpointing. Only applies when Enhanced VAD is enabled.",
        adaptThreshLabel: "Adaptive Threshold",
        adaptThreshDesc: "Adapt energy threshold based on observed noise floor.",
        adaptThreshTooltip: "When enabled, engine VAD raises the effective energy threshold in noisy environments so background noise doesn’t trigger speech.",
        noiseAdaptRateLabel: "Noise Adaptation Rate",
        noiseAdaptRateTooltip: "How quickly the adaptive threshold reacts to background noise (0.0–1.0). Higher reacts faster but can over-adjust on short noise bursts.",
        engineVadTitle: "Engine VAD (WebRTC)",
        engineVadDesc: "Engine-side fallback heuristics (barge-in + safety), using WebRTC VAD when available.",
        enableEngineFallbackLabel: "Enable Engine Fallback",
        enableEngineFallbackDesc: "Allow periodic forwarding / heuristics during extended silence (engine-side).",
        enableEngineFallbackTooltip: "If the engine believes the caller is silent for too long, it periodically lets audio through to avoid getting “stuck” on mis-detected silence. Does not affect providers that continuously stream audio.",
        fallbackIntervalLabel: "Fallback Interval (ms)",
        fallbackIntervalTooltip: "After this much detected silence, engine may periodically allow audio through for robustness (default: 1500ms). Increase to reduce background noise leakage; decrease if calls feel “stuck”.",
        aggressivenessLabel: "Aggressiveness (0-3)",
        aggressivenessTooltip: "WebRTC VAD aggressiveness (0–3). Higher = more aggressive silence detection (fewer false speech triggers) but may miss quiet speech.",
        startFramesLabel: "Start Frames",
        startFramesTooltip: "Number of consecutive “speech” frames needed to declare speech started. Higher reduces false starts but increases detection latency.",
        endSilFramesLabel: "End Silence Frames",
        endSilFramesTooltip: "Number of consecutive “silence” frames needed to declare speech ended. Higher avoids cutting off trailing words but increases tail latency.",
        utteranceTitle: "Utterance Controls",
        utteranceDesc: "Fine-grained utterance boundary tuning for engine-side heuristics.",
        uttExpertLabel: "Utterance Expert Settings",
        uttExpertDesc: "Enable editing of low-level utterance timing and buffer controls.",
        uttExpertWarn: "Warning: these controls can clip speech, delay turn-taking, or over-buffer audio if tuned aggressively.",
        uttExpertReadOnly: "Expert values are visible and read-only until enabled.",
        minUttDurationLabel: "Min Utterance Duration (ms)",
        minUttDurationTooltip: "Minimum duration to consider detected speech a valid utterance.",
        maxUttDurationLabel: "Max Utterance Duration (ms)",
        maxUttDurationTooltip: "Hard cap for a single utterance before forced boundary handling.",
        uttPadLabel: "Utterance Padding (ms)",
        uttPadTooltip: "Extra audio kept around utterance boundaries for naturalness.",
        fallbackBufLabel: "Fallback Buffer Size (bytes)",
        fallbackBufTooltip: "Internal fallback buffer size used by engine-side VAD fallback paths.",
        upstreamSquelchTitle: "Upstream Squelch",
        upstreamSquelchDesc: "Optional upstream noise squelch for continuous-audio providers with server-side VAD.",
        enableUpsqLabel: "Enable Upstream Squelch",
        enableUpsqDesc: "Replace non-speech frames with silence for server-VAD providers.",
        enableUpsqTooltip: "When enabled, the AI Engine analyzes inbound PCM16 energy and replaces low-energy/noise frames with silence before forwarding audio to providers that require continuous audio and have native VAD. This can improve end-of-turn detection in noisy environments, but overly aggressive settings can clip quiet speech.",
        baseRmsLabel: "Base RMS Threshold",
        baseRmsTooltip: "Minimum RMS threshold in PCM16 space. Higher blocks more low-energy audio (less noise leakage) but may suppress quiet callers.",
        noiseFactorLabel: "Noise Factor",
        noiseFactorTooltip: "Dynamic threshold multiplier: threshold = max(base_rms, noise_floor_rms × noise_factor). Increase to be more conservative about what counts as speech.",
        noiseEmaAlphaLabel: "Noise EMA Alpha",
        noiseEmaAlphaTooltip: "Noise floor smoothing factor (0–1). Higher adapts faster to changing background noise but can overreact to short bursts.",
        minSpeechFramesLabel: "Min Speech Frames",
        minSpeechFramesTooltip: "Hysteresis: number of consecutive speech frames required before the engine considers the caller “speaking”. Higher reduces false positives but can increase detection latency.",
        upsqEndSilFramesLabel: "End Silence Frames",
        upsqEndSilFramesTooltip: "Hysteresis: number of consecutive silence frames required to exit speaking state. Higher avoids toggling during noise, but may keep speech ‘open’ longer."
    };
};

addKeys(j_en);
fs.writeFileSync(jp_en, JSON.stringify(j_en, null, 4));

const jp_ru = 'c:/Users/sudxx/OneDrive/Desktop/Asterisk-AI-Voice-Agent/admin_ui/frontend/src/locales/ru.json';
const j_ru = JSON.parse(fs.readFileSync(jp_ru, 'utf8'));
addKeys(j_ru);
fs.writeFileSync(jp_ru, JSON.stringify(j_ru, null, 4));

console.log('Done!');
